name: workflow_01
# To get a trigger on every push in this repo in any branch
on: 
  push:    
jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: Running single command in Job1
        run: echo "This is my github workflow"
      - name: Cheking OS release for Github Hosted Runner
        run: cat /etc/os-release
      - name: Calling Sleep
        run: sleep 20
  job2:
    name: JOB2
    runs-on: ubuntu-latest
    steps:
      - name: Checking the hostname for the runner
        run: hostname
      - name: running multiple commands
        run: |
          echo "Hello from KAS"
          echo "Current time is 'date'"
          sleep 20
  job3:
    name: JOB3
    needs: job1
    runs-on: windows-latest
    steps:
      - name: Job with single dependency
        run: sleep 20
      - name: Checking runner info
        shell: pwsh
        run: get-computerinfo
  job4:
    name: JOB4
    needs: [job1, job2, job3]
    runs-on: macos-latest
    steps:
      - name: Job for multiple dependencies
        run: sleep 10
      - name: Checking runner info
        run: sw_vers
      
      
      
          
      
    



